# Generated by Django 6.1 on 2026-08-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('swimming', 'Swimming'), ('running', 'Running'), ('cycling', 'Cycling')])),
                ('started_at', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
