# Generated by Django 6.1 on 2026-08-29 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('swimming', 'Swimming'), ('running', 'Running'), ('cycling', 'Cycling')], null=True),
        ),
        migrations.CreateModel(
            name='WorkoutSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heart_rate', models.PositiveSmallIntegerField()),
                ('speed', models.FloatField()),
                ('cadence', models.PositiveSmallIntegerField()),
                ('power', models.PositiveSmallIntegerField()),
                ('elevation', models.FloatField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='workouts.workout')),
            ],
        ),
    ]
